// Package polymorphicrelation adds a single-parent, multi-collection relation to PocketBase.
package polymorphicrelation

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"slices"

	validation "github.com/pocketbase/ozzo-validation/v4"
	"github.com/pocketbase/pocketbase/core"
)

const Type = "polymorphicRelation"

type DeletePolicy string

const (
	Restrict DeletePolicy = "restrict"
	SetNull  DeletePolicy = "setNull"
	Cascade  DeletePolicy = "cascade"
)

// Reference is the public value of a polymorphic relation. A nil reference means no parent.
type Reference struct {
	CollectionID string `json:"collectionId"`
	RecordID     string `json:"recordId"`
}

// Field embeds the usual PocketBase JSON field attributes (Name, Id, Required, Hidden, Help).
// Relations is generated by the plugin and maps collection IDs to managed field names.
type Field struct {
	core.JSONField
	CollectionIDs []string          `json:"collectionIds" form:"collectionIds"`
	OnDelete      DeletePolicy      `json:"onDelete" form:"onDelete"`
	Relations     map[string]string `json:"relations" form:"relations"`
}

func init() { core.Fields[Type] = func() core.Field { return &Field{} } }

func (f *Field) Type() string                { return Type }
func (f *Field) CalculateMaxBodySize() int64 { return 1024 }

// Populate companions immediately: the Records API evaluates CreateRule against
// a virtual record before model hooks run. They must already reflect the input.
func (f *Field) FindSetter(key string) core.SetterFunc {
	if key != f.Name {
		return nil
	}
	return func(r *core.Record, raw any) {
		value, err := f.JSONField.PrepareValue(r, raw)
		if err != nil {
			r.SetRaw(f.Name, raw)
			return
		}
		r.SetRaw(f.Name, value)
		ref, err := f.reference(r)
		if err != nil {
			return
		}
		for _, id := range f.CollectionIDs {
			value := ""
			if ref != nil && ref.CollectionID == id {
				value = ref.RecordID
			}
			r.SetRaw(ServiceFieldName(f.Id, id), value)
		}
	}
}

// ServiceFieldName stays unchanged when either the public field or collection is renamed.
func ServiceFieldName(fieldID, collectionID string) string {
	hash := sha256.Sum256([]byte(fieldID + "\x00" + collectionID))
	return "pmr_" + hex.EncodeToString(hash[:12])
}

func (f *Field) policy() DeletePolicy {
	if f.OnDelete == "" {
		return Restrict
	}
	return f.OnDelete
}

func (f *Field) reference(record *core.Record) (*Reference, error) {
	data, err := json.Marshal(record.GetRaw(f.Name))
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err = json.Unmarshal(data, &obj); err != nil {
		return nil, fmt.Errorf("expected a reference object or null")
	}
	if obj == nil {
		return nil, nil
	}
	if len(obj) != 2 || obj["collectionId"] == nil || obj["recordId"] == nil {
		return nil, fmt.Errorf("expected collectionId and recordId")
	}
	var ref Reference
	if err = json.Unmarshal(data, &ref); err != nil || ref.CollectionID == "" || ref.RecordID == "" {
		return nil, fmt.Errorf("collectionId and recordId must be nonempty strings")
	}
	return &ref, nil
}

func (f *Field) ValidateSettings(ctx context.Context, app core.App, c *core.Collection) error {
	if err := f.JSONField.ValidateSettings(ctx, app, c); err != nil {
		return err
	}
	if c.System || c.IsView() {
		return fmt.Errorf("polymorphic relations require a non-system base or auth collection")
	}
	if len(f.CollectionIDs) == 0 {
		return validation.Errors{"collectionIds": validation.NewError("required", "Select at least one collection.")}
	}
	seen := map[string]bool{}
	for _, id := range f.CollectionIDs {
		if seen[id] {
			return fmt.Errorf("duplicate collection %q", id)
		}
		seen[id] = true
		target, err := app.FindCollectionByNameOrId(id)
		if err != nil || target.Id != id || target.System || target.IsView() {
			return validation.Errors{"collectionIds": validation.NewError("invalid_collection", "Select existing non-system base or auth collections.")}
		}
	}
	if !slices.Contains([]DeletePolicy{Restrict, SetNull, Cascade}, f.policy()) {
		return fmt.Errorf("invalid onDelete policy")
	}
	if f.Required && f.policy() == SetNull {
		return validation.Errors{"onDelete": validation.NewError("required_relation", "A required relation cannot use setNull.")}
	}
	return nil
}

func (f *Field) ValidateValue(ctx context.Context, app core.App, r *core.Record) error {
	if err := f.JSONField.ValidateValue(ctx, app, r); err != nil {
		return err
	}
	ref, err := f.reference(r)
	if err != nil {
		return validation.NewError("invalid_reference", err.Error())
	}
	if ref == nil {
		if f.Required {
			return validation.ErrRequired
		}
		return nil
	}
	if !slices.Contains(f.CollectionIDs, ref.CollectionID) {
		return validation.NewError("invalid_collection", "The parent collection is not allowed.")
	}
	if _, err := app.FindRecordById(ref.CollectionID, ref.RecordID); err != nil {
		return validation.NewError("missing_parent", "The parent record does not exist.")
	}
	return nil
}
