const $ = id => document.getElementById(id);
const labels = {pending:'Переход',lead:'Новая заявка',hold:'Холд',approved:'Подтверждено',rejected:'Отклонено'};
let records=[], editing='';
const showError=(id,error)=>{ $(id).textContent=error?.message || ''; $(id).hidden=!error; };
async function api(path,method='GET',body){const response=await fetch(path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);return result;}
function element(tag,text,cls){const node=document.createElement(tag);if(text!=null)node.textContent=text;if(cls)node.className=cls;return node;}
function render(){const rows=records.filter(r=>(!$('filter').value||r.status===$('filter').value)&&r.id.includes($('search').value.trim())).toReversed();$('rows').replaceChildren();$('count').textContent=`Заявок: ${rows.length}`;$('empty').hidden=rows.length>0;
 for(const row of rows){const tr=element('tr');const first=element('td',row.id);first.append(element('small',new Date(row.createdAt).toLocaleString('ru')));tr.append(first);const status=element('td');status.append(element('span',labels[row.status],`badge ${row.status}`));tr.append(status,element('td',`${row.amount} ${row.currency}`));const delivery=element('td',row.delivery);delivery.append(element('small',row.sentAt?`${new Date(row.sentAt).toLocaleString('ru')} · попыток: ${row.attempts}`:'Отправится при смене статуса'));tr.append(delivery);const actions=element('td');const wrap=element('div',null,'row-actions');const edit=element('button','Изменить');edit.onclick=()=>{editing=row.id;$('editing-id').textContent=row.id;$('status').value=row.status==='pending'?'lead':row.status;$('amount').value=row.amount;$('currency').value=row.currency;showError('status-error',null);$('editor').showModal();};wrap.append(edit);if(row.status!=='pending'){const retry=element('button','Повторить');retry.onclick=async()=>{if(row.responseCode===200&&!confirm('Этот постбек уже доставлен. Повтор может ещё раз начислить Revenue. Отправить повторно?'))return;retry.disabled=true;try{await api(`/api/conversions/${row.id}/retry`,'POST',{});await load();}catch(e){showError('error',e);}finally{retry.disabled=false;}};wrap.append(retry);}actions.append(wrap);tr.append(actions);$('rows').append(tr);}}
async function load(){showError('error',null);try{records=await api('/api/conversions');render();}catch(e){showError('error',e);}}
$('refresh').onclick=load;$('filter').onchange=render;$('search').oninput=render;
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
$('status-form').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;showError('status-error',null);try{await api(`/api/conversions/${editing}/status`,'POST',{status:$('status').value,amount:$('amount').value,currency:$('currency').value});$('editor').close();await load();}catch(e){showError('status-error',e);}finally{button.disabled=false;}};
$('settings-button').onclick=async()=>{try{const cfg=await api('/api/settings');$('postback-url').value=cfg.url;$('method').value=cfg.method;$('secret-location').value=cfg.secretLocation;$('secret-name').value=cfg.secretName;$('secret').value='';$('secret-state').textContent=cfg.hasSecret?'Секрет сохранён. Введите новое значение только для замены.':'Секрет не задан.';showError('settings-error',null);$('settings').showModal();}catch(e){showError('error',e);}};
$('settings-form').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;showError('settings-error',null);try{await api('/api/settings','PUT',{url:$('postback-url').value,method:$('method').value,secretLocation:$('secret-location').value,secretName:$('secret-name').value,secret:$('secret').value});$('settings').close();}catch(e){showError('settings-error',e);}finally{button.disabled=false;}};
let theme=localStorage.getItem('demo-partner-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');document.documentElement.dataset.theme=theme;$('theme').onclick=()=>{theme=theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;localStorage.setItem('demo-partner-theme',theme);};load();
