name: dynamic_link
description: Platform-independent dynamic link models.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.2

dependencies:
  equatable: ^2.1.0

dev_dependencies:
  test: ^1.31.1
