// Generated by typedconfig. Do not edit. Schema version 1.

sealed class ScreenItem {
  const ScreenItem(this.id);
  final String id;
  factory ScreenItem.fromJson(Map<String, dynamic> json) {
    final id = _ScreenText(json['id']);
    final data = _ScreenObject(json['data']);
    return switch (json['type']) {
      'heading' => ScreenHeading1(id, ScreenHeading1Data.fromJson(data)),
      'offer' => ScreenOffer2(id, ScreenOffer2Data.fromJson(data)),
      'group' => ScreenGroup3(id, ScreenGroup3Data.fromJson(data)),
      _ => throw const FormatException('Unknown configuration item type'),
    };
  }
}

final class ScreenHeading1 extends ScreenItem {
  const ScreenHeading1(super.id, this.data);
  final ScreenHeading1Data data;
}

final class ScreenHeading1Data {
  const ScreenHeading1Data(this.textValue, this.styleValue);
  final String textValue;
  final ScreenHeading1DataStyle2? styleValue;
  factory ScreenHeading1Data.fromJson(Map<String, dynamic> json) => ScreenHeading1Data(_ScreenText(json['text']), json['style'] == null ? null : ScreenHeading1DataStyle2.fromJson(_ScreenObject(json['style'])));
}

final class ScreenHeading1DataStyle2 {
  const ScreenHeading1DataStyle2(this.compactValue);
  final bool compactValue;
  factory ScreenHeading1DataStyle2.fromJson(Map<String, dynamic> json) => ScreenHeading1DataStyle2(_ScreenBool(json['compact']));
}

final class ScreenOffer2 extends ScreenItem {
  const ScreenOffer2(super.id, this.data);
  final ScreenOffer2Data data;
}

final class ScreenOffer2Data {
  const ScreenOffer2Data(this.offerValue);
  final ScreenOffer2DataOffer1 offerValue;
  factory ScreenOffer2Data.fromJson(Map<String, dynamic> json) => ScreenOffer2Data(ScreenOffer2DataOffer1.fromJson(_ScreenObject(json['offer'])));
}

final class ScreenOffer2DataOffer1 {
  const ScreenOffer2DataOffer1(this.titleValue, this.ratingValue);
  final String titleValue;
  final num ratingValue;
  factory ScreenOffer2DataOffer1.fromJson(Map<String, dynamic> json) => ScreenOffer2DataOffer1(_ScreenText(json['title']), _ScreenNumber(json['rating']));
}

final class ScreenGroup3 extends ScreenItem {
  const ScreenGroup3(super.id, this.data);
  final ScreenGroup3Data data;
}

final class ScreenGroup3Data {
  const ScreenGroup3Data(this.offersValue);
  final List<ScreenGroup3DataOffers1Entry> offersValue;
  factory ScreenGroup3Data.fromJson(Map<String, dynamic> json) => ScreenGroup3Data(_ScreenList<ScreenGroup3DataOffers1Entry>(json['offers'], (value) => ScreenGroup3DataOffers1Entry.fromJson(_ScreenObject(value))));
}

final class ScreenGroup3DataOffers1Entry {
  const ScreenGroup3DataOffers1Entry(this.idValue, this.collectionIdValue);
  final String idValue;
  final String collectionIdValue;
  factory ScreenGroup3DataOffers1Entry.fromJson(Map<String, dynamic> json) => ScreenGroup3DataOffers1Entry(_ScreenText(json['id']), _ScreenText(json['collectionId']));
}

Map<String, dynamic> _ScreenObject(Object? value) {
  if (value is! Map<String, dynamic>) throw const FormatException('Expected object');
  return value;
}
String _ScreenText(Object? value) {
  if (value is! String) throw const FormatException('Expected string');
  return value;
}
num _ScreenNumber(Object? value) {
  if (value is! num || !value.isFinite) throw const FormatException('Expected finite number');
  return value;
}
bool _ScreenBool(Object? value) {
  if (value is! bool) throw const FormatException('Expected boolean');
  return value;
}
List<T> _ScreenList<T>(Object? value, T Function(Object?) decode) {
  if (value is! List) throw const FormatException('Expected list');
  return List<T>.unmodifiable(value.map(decode));
}
