package typedconfig

import (
	"bytes"
	"fmt"
	"io"
	"regexp"
	"strings"
)

// GenerateDart generates dependency-free, immutable response DTOs for a schema.
// The DTOs decode resolved Records API items, not the admin's source references.
// Property getters use a Value suffix to avoid Dart/Object reserved names.
func GenerateDart(w io.Writer, s Schema, name string) error {
	if !regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`).MatchString(name) || s.Version < 1 || len(s.Types) == 0 {
		return fmt.Errorf("typedConfig: invalid Dart class name or schema")
	}
	g := dartGenerator{schema: s, prefix: name}
	root := name + "Item"
	fmt.Fprintf(&g.out, "// Generated by typedconfig. Do not edit. Schema version %d.\n\n", s.Version)
	fmt.Fprintf(&g.out, "sealed class %s {\n  const %s(this.id);\n  final String id;\n  factory %s.fromJson(Map<String, dynamic> json) {\n    final id = _%sText(json['id']);\n    final data = _%sObject(json['data']);\n    return switch (json['type']) {\n", root, root, root, name, name)
	names := map[string]bool{}
	for i, b := range s.Types {
		if !validKey(b.Key) || names[b.Key] {
			return fmt.Errorf("typedConfig: invalid or duplicate item type")
		}
		names[b.Key] = true
		class := fmt.Sprintf("%s%s%d", name, dartName(b.Key), i+1)
		fmt.Fprintf(&g.out, "      '%s' => %s(id, %sData.fromJson(data)),\n", b.Key, class, class)
	}
	fmt.Fprint(&g.out, "      _ => throw const FormatException('Unknown configuration item type'),\n    };\n  }\n}\n\n")
	for i, b := range s.Types {
		class := fmt.Sprintf("%s%s%d", name, dartName(b.Key), i+1)
		fmt.Fprintf(&g.out, "final class %s extends %s {\n  const %s(super.id, this.data);\n  final %sData data;\n}\n\n", class, root, class, class)
		if err := g.object(class+"Data", b.Fields, 0, map[string]bool{}); err != nil {
			return err
		}
	}
	fmt.Fprintf(&g.out, `Map<String, dynamic> _%[1]sObject(Object? value) {
  if (value is! Map<String, dynamic>) throw const FormatException('Expected object');
  return value;
}
String _%[1]sText(Object? value) {
  if (value is! String) throw const FormatException('Expected string');
  return value;
}
num _%[1]sNumber(Object? value) {
  if (value is! num || !value.isFinite) throw const FormatException('Expected finite number');
  return value;
}
int _%[1]sInteger(Object? value) {
  final number = _%[1]sNumber(value);
  if (number != number.truncateToDouble()) throw const FormatException('Expected integer');
  return number.toInt();
}
bool _%[1]sBool(Object? value) {
  if (value is! bool) throw const FormatException('Expected boolean');
  return value;
}
List<T> _%[1]sList<T>(Object? value, T Function(Object?) decode) {
  if (value is! List) throw const FormatException('Expected list');
  return List<T>.unmodifiable(value.map(decode));
}
String _%[1]sEnum(Object? value, List<String> choices) {
  final text = _%[1]sText(value);
  if (!choices.contains(text)) throw const FormatException('Unknown enum value');
  return text;
}
`, name)
	// Only emit helpers actually used by this schema (keeps dart analyze clean).
	output := g.out.String()
	for _, helper := range []string{"Integer", "Number", "Bool", "List", "Enum"} {
		marker := "_" + name + helper
		if strings.Count(output, marker) == 1 {
			lines := strings.Split(output, "\n")
			start := -1
			for i, line := range lines {
				if strings.Contains(line, marker) {
					start = i
				}
				if start >= 0 && line == "}" {
					lines = append(lines[:start], lines[i+1:]...)
					break
				}
			}
			output = strings.Join(lines, "\n")
		}
	}
	_, err := io.WriteString(w, output)
	return err
}

type dartGenerator struct {
	schema Schema
	prefix string
	out    bytes.Buffer
}

func dartName(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool { return r == '-' || r == '_' })
	for i, p := range parts {
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}
func (g *dartGenerator) object(class string, ps []Property, depth int, seen map[string]bool) error {
	if depth > 12 {
		return fmt.Errorf("typedConfig: recursive schema")
	}
	var nested bytes.Buffer
	fields := []string{}
	parsers := []string{}
	names := map[string]bool{}
	for i, p := range ps {
		if !validKey(p.Name) {
			return fmt.Errorf("typedConfig: invalid property")
		}
		property := dartName(p.Name)
		property = strings.ToLower(property[:1]) + property[1:] + "Value"
		if names[property] {
			return fmt.Errorf("typedConfig: property names collide in Dart")
		}
		names[property] = true
		before := g.out.Len()
		typ, parser, err := g.value(p.Node, fmt.Sprintf("%s%s%d", class, dartName(p.Name), i+1), "json['"+p.Name+"']", depth+1, seen)
		if err != nil {
			return err
		}
		nested.Write(g.out.Bytes()[before:])
		g.out.Truncate(before)
		if !p.Required {
			typ += "?"
			parser = "json['" + p.Name + "'] == null ? null : " + parser
		}
		fields = append(fields, fmt.Sprintf("  final %s %s;", typ, property))
		parsers = append(parsers, parser)
	}
	fmt.Fprintf(&g.out, "final class %s {\n", class)
	fmt.Fprintf(&g.out, "  const %s(", class)
	for i, p := range ps {
		if i > 0 {
			fmt.Fprint(&g.out, ", ")
		}
		property := dartName(p.Name)
		fmt.Fprintf(&g.out, "this.%sValue", strings.ToLower(property[:1])+property[1:])
	}
	fmt.Fprint(&g.out, ");\n")
	for _, line := range fields {
		fmt.Fprintln(&g.out, line)
	}
	fmt.Fprintf(&g.out, "  factory %s.fromJson(Map<String, dynamic> json) => %s(%s);\n}\n\n", class, class, strings.Join(parsers, ", "))
	g.out.Write(nested.Bytes())
	return nil
}
func (g *dartGenerator) value(n Node, class, expr string, depth int, seen map[string]bool) (string, string, error) {
	if depth > 12 {
		return "", "", fmt.Errorf("typedConfig: recursive schema")
	}
	if n.Ref != "" {
		d, ok := g.schema.Definitions[n.Ref]
		if !ok || seen[n.Ref] {
			return "", "", fmt.Errorf("typedConfig: invalid reference")
		}
		next := map[string]bool{}
		for k, v := range seen {
			next[k] = v
		}
		next[n.Ref] = true
		return g.value(d, class, expr, depth+1, next)
	}
	helper := func(kind string) string { return "_" + g.prefix + kind + "(" + expr + ")" }
	switch n.Kind {
	case "string":
		return "String", helper("Text"), nil
	case "enum":
		choices := []string{}
		for _, choice := range n.Options {
			choice = strings.NewReplacer("\\", "\\\\", "'", "\\'", "$", "\\$", "\n", "\\n", "\r", "\\r").Replace(choice)
			choices = append(choices, "'"+choice+"'")
		}
		return "String", "_" + g.prefix + "Enum(" + expr + ", [" + strings.Join(choices, ", ") + "])", nil
	case "number":
		return "num", helper("Number"), nil
	case "integer":
		return "int", helper("Integer"), nil
	case "boolean":
		return "bool", helper("Bool"), nil
	case "array":
		if n.Items == nil {
			return "", "", fmt.Errorf("typedConfig: array item type missing")
		}
		typ, parser, err := g.value(*n.Items, class+"Entry", "value", depth+1, seen)
		return "List<" + typ + ">", "_" + g.prefix + "List<" + typ + ">(" + expr + ", (value) => " + parser + ")", err
	case "object", "reference":
		ps := n.Fields
		if n.Kind == "reference" && (n.Source == nil || len(n.Source.Mapping) == 0) {
			ps = []Property{{Name: "id", Required: true, Node: Node{Kind: "string"}}, {Name: "collectionId", Required: true, Node: Node{Kind: "string"}}}
		}
		if err := g.object(class, ps, depth+1, seen); err != nil {
			return "", "", err
		}
		return class, class + ".fromJson(" + helper("Object") + ")", nil
	}
	return "", "", fmt.Errorf("typedConfig: unsupported kind %q", n.Kind)
}
